<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314221846 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE fach (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visible BOOLEAN DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, dn VARCHAR(500) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE klasse (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visible BOOLEAN DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, dn VARCHAR(500) DEFAULT NULL, klassenlehrer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_63D43DFBF674DCEF ON klasse (klassenlehrer_id)');
        $this->addSql('CREATE TABLE klasse_lehrer (klasse_id INT NOT NULL, lehrer_id INT NOT NULL, PRIMARY KEY (klasse_id, lehrer_id))');
        $this->addSql('CREATE INDEX IDX_E208663834860711 ON klasse_lehrer (klasse_id)');
        $this->addSql('CREATE INDEX IDX_E20866383302EA81 ON klasse_lehrer (lehrer_id)');
        $this->addSql('CREATE TABLE kompetenz (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, fach_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_608A8112FA2B40D ON kompetenz (fach_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_608A81125E237E06 ON kompetenz (name)');
        $this->addSql('CREATE TABLE kompetenzraster (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, a INT DEFAULT NULL, b INT DEFAULT NULL, c INT DEFAULT NULL, d INT DEFAULT NULL, e INT DEFAULT NULL, f INT DEFAULT NULL, g INT DEFAULT NULL, h INT DEFAULT NULL, i INT DEFAULT NULL, schueler_id INT NOT NULL, kompetenz_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D722B4559AC0A64E ON kompetenzraster (schueler_id)');
        $this->addSql('CREATE INDEX IDX_D722B4555616717A ON kompetenzraster (kompetenz_id)');
        $this->addSql('CREATE TABLE schueler (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visible BOOLEAN DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, dn VARCHAR(500) DEFAULT NULL, klasse_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C382476D34860711 ON schueler (klasse_id)');
        $this->addSql('ALTER TABLE klasse ADD CONSTRAINT FK_63D43DFBF674DCEF FOREIGN KEY (klassenlehrer_id) REFERENCES lehrer (id)');
        $this->addSql('ALTER TABLE klasse_lehrer ADD CONSTRAINT FK_E208663834860711 FOREIGN KEY (klasse_id) REFERENCES klasse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE klasse_lehrer ADD CONSTRAINT FK_E20866383302EA81 FOREIGN KEY (lehrer_id) REFERENCES lehrer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kompetenz ADD CONSTRAINT FK_608A8112FA2B40D FOREIGN KEY (fach_id) REFERENCES fach (id)');
        $this->addSql('ALTER TABLE kompetenzraster ADD CONSTRAINT FK_D722B4559AC0A64E FOREIGN KEY (schueler_id) REFERENCES schueler (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kompetenzraster ADD CONSTRAINT FK_D722B4555616717A FOREIGN KEY (kompetenz_id) REFERENCES kompetenz (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schueler ADD CONSTRAINT FK_C382476D34860711 FOREIGN KEY (klasse_id) REFERENCES klasse (id)');
        $this->addSql('ALTER TABLE lehrer ADD visible BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE lehrer ADD label VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE lehrer ADD dn VARCHAR(500) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE klasse DROP CONSTRAINT FK_63D43DFBF674DCEF');
        $this->addSql('ALTER TABLE klasse_lehrer DROP CONSTRAINT FK_E208663834860711');
        $this->addSql('ALTER TABLE klasse_lehrer DROP CONSTRAINT FK_E20866383302EA81');
        $this->addSql('ALTER TABLE kompetenz DROP CONSTRAINT FK_608A8112FA2B40D');
        $this->addSql('ALTER TABLE kompetenzraster DROP CONSTRAINT FK_D722B4559AC0A64E');
        $this->addSql('ALTER TABLE kompetenzraster DROP CONSTRAINT FK_D722B4555616717A');
        $this->addSql('ALTER TABLE schueler DROP CONSTRAINT FK_C382476D34860711');
        $this->addSql('DROP TABLE fach');
        $this->addSql('DROP TABLE klasse');
        $this->addSql('DROP TABLE klasse_lehrer');
        $this->addSql('DROP TABLE kompetenz');
        $this->addSql('DROP TABLE kompetenzraster');
        $this->addSql('DROP TABLE schueler');
        $this->addSql('ALTER TABLE lehrer DROP visible');
        $this->addSql('ALTER TABLE lehrer DROP label');
        $this->addSql('ALTER TABLE lehrer DROP dn');
    }
}
